Sobre las elecciones alimentarias de estudiantes universitarios; el objetivo fue intentar comprender cuán importante es la información nutricional.

In [47]:
import pandas as pd
import numpy as np

In [48]:
import re

def limpiar_peso(valor):
    valor = str(valor)
    
    solo_numeros = re.sub(r"\D", "", valor)
    if(len(solo_numeros)==0):
        return np.nan
    else:
        return int(solo_numeros)
    
def limpiar_gpa(valor):
    valor = str(valor)
    
    # Eliminamos cualquier cosa que NO sea un dígito [0-9] o un punto [.]
    solo_numeros = re.sub(r'[^0-9.]', "", valor)
    
    if len(solo_numeros) == 0:
        return np.nan
    else:
        # Usamos float() para mantener los decimales del GPA
        return float(solo_numeros)

In [49]:
df = pd.read_csv('food_coded.csv')

In [50]:
pd.set_option('display.max_columns', None)
df.head()

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.4       2          1               430           NaN           315.0   
1  3.654       1          1               610           3.0           420.0   
2    3.3       1          1               720           4.0           420.0   
3    3.2       1          1               430           3.0           420.0   
4    3.5       1          1               720           2.0           420.0   

   coffee                      comfort_food        comfort_food_reasons  \
0       1                              none       we dont have comfort    
1       2       chocolate, chips, ice cream        Stress, bored, anger   
2       2   frozen yogurt, pizza, fast food             stress, sadness   
3       2  Pizza, Mac and cheese, ice cream                     Boredom   
4       2      Ice cream, chocolate, chips   Stress, boredom, cravings    

   comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  cuisine  \
0                         9.0   2.0                             9      NaN   
1                         1.0   3.0                             1      1.0   
2                         1.0   1.0                             1      3.0   
3                         2.0   2.0                             2      2.0   
4                         1.0   1.0                             1      2.0   

                                        diet_current  diet_current_coded  \
0                              eat good and exercise                   1   
1  I eat about three times a day with some snacks...                   2   
2  toast and fruit for breakfast, salad for lunch...                   3   
3  College diet, cheap and easy foods most nights...                   2   
4  I try to eat healthy but often struggle becaus...                   2   

   drink                                     eating_changes  \
0    1.0                                        eat faster    
1    2.0                        I eat out more than usual.    
2    1.0  sometimes choosing to eat fast food instead of...   
3    2.0     Accepting cheap and premade/store bought foods   
4    2.0  I have eaten generally the same foods but I do...   

   eating_changes_coded  eating_changes_coded1  eating_out  employment  \
0                     1                      1           3         3.0   
1                     1                      2           2         2.0   
2                     1                      3           2         3.0   
3                     1                      3           2         3.0   
4                     3                      4           2         2.0   

   ethnic_food  exercise  father_education father_profession     fav_cuisine  \
0            1       1.0               5.0         profesor   Arabic cuisine   
1            4       1.0               2.0    Self employed          Italian   
2            5       2.0               2.0     owns business         italian   
3            5       3.0               2.0         Mechanic         Turkish    
4            4       1.0               4.0                IT        Italian    

   fav_cuisine_coded  fav_food                                food_childhood  \
0                  3       1.0                            rice  and chicken    
1                  1       1.0  chicken and biscuits, beef soup, baked beans   
2                  1       3.0                  mac and cheese, pizza, tacos   
3                  3       1.0                 Beef stroganoff, tacos, pizza   
4                  1       3.0                 Pasta, chicken tender, pizza    

   fries  fruit_day  grade_level  greek_food  healthy_feeling  \
0      2          5            2           5                2   
1      1          4            4           4                5   
2      1          5            3           5                6   
3      2          4            4           5                7   
4      1          4            4          

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           123 non-null    object 
 1   Gender                        125 non-null    int64  
 2   breakfast                     125 non-null    int64  
 3   calories_chicken              125 non-null    int64  
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64  
 7   comfort_food                  124 non-null    object 
 8   comfort_food_reasons          123 non-null    object 
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64  
 12  cuisine                       108 non-null    float64
 13  diet_

In [52]:
df['weight'].unique()

array(['187', '155', "I'm not answering this. ", 'Not sure, 240', '190',
       '180', '137', '125', '116', '110', '264', '123', '185', '145',
       '170', '135', '165', '175', '195', '105', '160', '167', '115',
       '205', nan, '128', '150', '140', '120', '100', '113', '168', '169',
       '200', '265', '192', '118', '210', '112', '144 lbs', '130', '127',
       '129', '260', '184', '230', '138', '156'], dtype=object)

In [53]:
df['weight'] = df['weight'].apply(limpiar_peso)
df['weight'].unique()

array([187., 155.,  nan, 240., 190., 180., 137., 125., 116., 110., 264.,
       123., 185., 145., 170., 135., 165., 175., 195., 105., 160., 167.,
       115., 205., 128., 150., 140., 120., 100., 113., 168., 169., 200.,
       265., 192., 118., 210., 112., 144., 130., 127., 129., 260., 184.,
       230., 138., 156.])

In [54]:
df['weight'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 125 entries, 0 to 124
Series name: weight
Non-Null Count  Dtype  
--------------  -----  
122 non-null    float64
dtypes: float64(1)
memory usage: 1.1 KB


In [55]:
df['weight'] = df['weight'].fillna(df['weight'].median())
df['weight'].unique()

array([187., 155., 240., 190., 180., 137., 125., 116., 110., 264., 123.,
       185., 145., 170., 135., 165., 175., 195., 105., 160., 167., 115.,
       205., 128., 150., 140., 120., 100., 113., 168., 169., 200., 265.,
       192., 118., 210., 112., 144., 130., 127., 129., 260., 184., 230.,
       138., 156.])

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           123 non-null    object 
 1   Gender                        125 non-null    int64  
 2   breakfast                     125 non-null    int64  
 3   calories_chicken              125 non-null    int64  
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64  
 7   comfort_food                  124 non-null    object 
 8   comfort_food_reasons          123 non-null    object 
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64  
 12  cuisine                       108 non-null    float64
 13  diet_

# RECONOCER OUTLIERS WEIGHT

In [57]:
df['weight'].describe()

count    125.000000
mean     158.952000
std       31.988621
min      100.000000
25%      135.000000
50%      155.000000
75%      180.000000
max      265.000000
Name: weight, dtype: float64

In [58]:
q1 = df['weight'].describe()['25%']
q3 = df['weight'].describe()['75%']
iqr = q3-q1

lower_fence = q1 - (1.5*iqr)
upper_fence = q3 + (1.5*iqr)
print(f"LOWER: {lower_fence}, UPPER: {upper_fence}")

LOWER: 67.5, UPPER: 247.5


In [59]:
condicion = (df['weight'] < 67.5) | (df['weight'] > 247.5)
df = df[~ condicion]
df

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0      2.4       2          1               430           NaN           315.0   
1    3.654       1          1               610           3.0           420.0   
2      3.3       1          1               720           4.0           420.0   
3      3.2       1          1               430           3.0           420.0   
4      3.5       1          1               720           2.0           420.0   
..     ...     ...        ...               ...           ...             ...   
120    3.5       1          1               610           4.0           420.0   
121      3       1          1               265           2.0           315.0   
122  3.882       1          1               720           NaN           420.0   
123      3       2          1               720           4.0           420.0   
124    3.9       1          1               430           NaN           315.0   

     coffee                             comfort_food  \
0         1                                     none   
1         2              chocolate, chips, ice cream   
2         2          frozen yogurt, pizza, fast food   
3         2         Pizza, Mac and cheese, ice cream   
4         2             Ice cream, chocolate, chips    
..      ...                                      ...   
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  cuisine  \
0                           9.0   2.0                             9      NaN   
1                           1.0   3.0                             1      1.0   
2                           1.0   1.0                             1      3.0   
3                           2.0   2.0                             2      2.0   
4                           1.0   1.0                             1      2.0   
..                          ...   ...                           ...      ...   
120                         NaN   3.0                             2      1.0   
121                         NaN   3.0                             3      NaN   
122                         NaN   3.0                             3      NaN   
123                         NaN   3.0                             7      1.0   
124                         NaN   NaN                             5      3.0   

                                          diet_current  diet_current_coded  \
0                                eat good and exercise                   1   
1    I eat about three times a day with some snacks...                   2   
2    toast and fruit for breakfast, salad for lunch...                   3   
3    College diet, cheap and easy foods most nights...                   2   
4    I try to eat healthy but often struggle becaus...                   2   
..                                                 ...                 ...   
120  My diet consists mainly of coffee, water, frui...                   2   
121  A college student with an imbalanced diet tryi...                   2   
122                             Rice, oatmeal, an

# LIMPIEZA GPA

In [60]:
df['GPA'].info()

<class 'pandas.core.series.Series'>
Index: 122 entries, 0 to 124
Series name: GPA
Non-Null Count  Dtype 
--------------  ----- 
120 non-null    object
dtypes: object(1)
memory usage: 1.9+ KB


In [61]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.6',
       '3.1', nan, '4', '3.4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.35', 'Personal ', '2.6',
       '3.67', '3.73', '3.79 bitch', '2.71', '3.75', '3.92', 'Unknown',
       '3.77', '3.63', '3.882'], dtype=object)

In [62]:
df['GPA'] = df['GPA'].apply(limpiar_gpa)
df['GPA'].unique()

array([2.4  , 3.654, 3.3  , 3.2  , 3.5  , 2.25 , 3.8  , 3.904, 3.6  ,
       3.1  ,   nan, 4.   , 3.4  , 2.2  , 3.87 , 3.7  , 3.9  , 2.8  ,
       3.   , 3.65 , 3.89 , 2.9  , 3.605, 3.83 , 3.35 , 2.6  , 3.67 ,
       3.73 , 3.79 , 2.71 , 3.75 , 3.92 , 3.77 , 3.63 , 3.882])

In [63]:
df

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.400       2          1               430           NaN           315.0   
1    3.654       1          1               610           3.0           420.0   
2    3.300       1          1               720           4.0           420.0   
3    3.200       1          1               430           3.0           420.0   
4    3.500       1          1               720           2.0           420.0   
..     ...     ...        ...               ...           ...             ...   
120  3.500       1          1               610           4.0           420.0   
121  3.000       1          1               265           2.0           315.0   
122  3.882       1          1               720           NaN           420.0   
123  3.000       2          1               720           4.0           420.0   
124  3.900       1          1               430           NaN           315.0   

     coffee                             comfort_food  \
0         1                                     none   
1         2              chocolate, chips, ice cream   
2         2          frozen yogurt, pizza, fast food   
3         2         Pizza, Mac and cheese, ice cream   
4         2             Ice cream, chocolate, chips    
..      ...                                      ...   
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  cuisine  \
0                           9.0   2.0                             9      NaN   
1                           1.0   3.0                             1      1.0   
2                           1.0   1.0                             1      3.0   
3                           2.0   2.0                             2      2.0   
4                           1.0   1.0                             1      2.0   
..                          ...   ...                           ...      ...   
120                         NaN   3.0                             2      1.0   
121                         NaN   3.0                             3      NaN   
122                         NaN   3.0                             3      NaN   
123                         NaN   3.0                             7      1.0   
124                         NaN   NaN                             5      3.0   

                                          diet_current  diet_current_coded  \
0                                eat good and exercise                   1   
1    I eat about three times a day with some snacks...                   2   
2    toast and fruit for breakfast, salad for lunch...                   3   
3    College diet, cheap and easy foods most nights...                   2   
4    I try to eat healthy but often struggle becaus...                   2   
..                                                 ...                 ...   
120  My diet consists mainly of coffee, water, frui...                   2   
121  A college student with an imbalanced diet tryi...                   2   
122                             Rice, oatmeal, an

In [64]:
df['GPA'] = df['GPA'].fillna(df['GPA'].median())

In [65]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [66]:
df['calories_day'] = df['calories_day'].fillna(df['calories_day'].median())
df['calories_day'].unique()

array([3., 4., 2.])

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           122 non-null    float64
 1   Gender                        122 non-null    int64  
 2   breakfast                     122 non-null    int64  
 3   calories_chicken              122 non-null    int64  
 4   calories_day                  122 non-null    float64
 5   calories_scone                121 non-null    float64
 6   coffee                        122 non-null    int64  
 7   comfort_food                  121 non-null    object 
 8   comfort_food_reasons          120 non-null    object 
 9   comfort_food_reasons_coded    103 non-null    float64
 10  cook                          119 non-null    float64
 11  comfort_food_reasons_coded.1  122 non-null    int64  
 12  cuisine                       106 non-null    float64
 13  diet_curre

In [68]:
df['comfort_food'].unique()

array(['none', 'chocolate, chips, ice cream',
       'frozen yogurt, pizza, fast food',
       'Pizza, Mac and cheese, ice cream', 'Ice cream, chocolate, chips ',
       'Candy, brownies and soda.',
       'Chocolate, ice cream, french fries, pretzels',
       'Ice cream, cheeseburgers, chips.', 'Donuts, ice cream, chips',
       'Mac and cheese, chocolate, and pasta ',
       'Pasta, grandma homemade chocolate cake anything homemade ',
       'chocolate, pasta, soup, chips, popcorn',
       'ice cream, cake, chocolate',
       'Pizza, fruit, spaghetti, chicken and Potatoes  ',
       'cookies, donuts, candy bars', 'Saltfish, Candy and Kit Kat ',
       'chips, cookies, ice cream', 'Chocolate, ice crea ',
       'pizza, wings, Chinese', 'Fast food, pizza, subs',
       'chocolate, sweets, ice cream', 'burgers, chips, cookies',
       'Chilli, soup, pot pie', 'Soup, pasta, brownies, cake',
       'chocolate, ice cream/milkshake, cookies',
       'Chips, ice cream, microwaveable foods ',

In [75]:
def limpiar_comfort_food(value):
    texto = re.sub(r"\\r", ",", value)
    return re.sub("/", ",", texto)
df['comfort_food'] = df['comfort_food'].apply(limpiar_comfort_food)
df['comfort_food'].unique()

TypeError: expected string or bytes-like object, got 'float'

In [ ]:
#df['income'] = df['income'].fillna(df['income'].median())


np.int64(0)